import Head from "next/head";
import { useRouter } from "next/router";
import Select from "../components/Select";
import en from "../locales/en";
import tr from "../locales/tr";

export default function Home() {
  const router = useRouter();
  const { locale } = router;
  const t = locale === "en" ? en : tr;

  return (
    <div className="bg-blue">
      <div className="bg-blue text-white w-full min-h-screen mx-auto max-w-3xl justify-between ">
        <div className="flex flex-row w-full space-x-8">
          <Head>
            <title>NextJS Multi-Language App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <h1 className="flex justify-between items-center py-3">
            NextJS Multi-Language App
          </h1>
          <Select />
        </div>
        <div>
          <div>{t.title}</div>
          <div>{t.content}</div>
        </div>
      </div>
    </div>
  );
}
